# -*- coding: utf-8 -*-
"""
Created on Thu Oct 14 15:30:05 2021
@author: pablo

Problem
An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.
Given a DNA string t corresponding to a coding strand, its transcribed RNA 
string u is formed by replacing all occurrences of 'T' in t with 'U' in u.
Given: A DNA string t having length at most 1000 nt.
Return: The transcribed RNA string of t.

"""
# Function
def transcribe_RNA(dna):
    
    rna = dna.replace("T","U")
    return print(rna)

# Test
s = "TCTAAAGCCCTCTATTACACTTCACTCCTGAGGACTGGCCTAACGACCCCGAGAACACCGTTCACAATTCATCCCGAAAGCAACCACGACGACCGGCGGCTTTCTCGTTTGGAGTTTTCGGGAGACACTTTCGGGCTTTTCACCTTCTCCTTGGCTACTGAACTGAAACCTGTCGTCGCTCATTTTCCGGGTTCTTATGACCATCGGACGTCACTGCACTCTTTTAATGGATGATCGTCAATCAGATCTTAATTCACGCACCAGCCGTCCACACTGTTGCTCAAGGCTTCCCCCGAGCCTACGGACCGTCAGATCATACTCAGTCTTCGTGTGACGCACACGGCACCGGCGTGGTAGGGATTCGCAGTACCTCATTCAGGTTAAGAATGATTCATGAGAGTTTGAATTATTTAGCGAGCCTCCGCGTTGAATGGAAGAGGAGGACCATCATTGTGCACTTATGACCTGGATGACACCGTCTTTACTTCTGAACGGTTGAACACTTCGCCTTGGCCTCGACCATTTGCGATTGGTTTTGATGCGACTTTTAGCGCAAGTAGTACGGGCGCCCTAAGAACTGATCCAAGAAGCGGGCGTCGAACACATTACCTGGGGATATCCCTAGTGGCCTGCCCATAGGACGATCATCCAGGTCTTAAAAGACCAATATCAATAGTGCATTACATTTGAGGAAGGCACAACGTTACCGGGGTTGGGAACACTGACCGGGCCGCTGAGGTCTAGGGTCCGGCCTGCAGAGCCAATACGGTTATCACGACCTCTCACACTTTTTTGAGTACGATGAGGCCTCTGGGGTGTAGGCCCCTCGTTCACAAGGGGATGGAGCGGGGCTTCAGGAGGCAAGAAATTAGCTATCGACTCACTAGAATAGCCAATACAGGACAGCCTAGCCTTGTGTTCGCAACCGCGAACTCTGCCATAAAG"
transcribe_RNA(s)